### ISSUE TITLE
Deploy 

### ISSUE THREAD

**Issue by carlosmoraes-dev** [RosanaMascena/Projeto-viajar-e-bom-demais#2]
Olá Rosana tudo bem? eu consegui acessar o seu projeto e ficou maravilhoso, mas ao tentar acessa-lo pelo link contido no Readme ele não está abrindo.

**Comment by RosanaMascena** [comment]
Oi @Carlos-Moraes2 tudo bem? Obrigada por me avisar. Eu preciso na verdade fazer uma geral nos meus readmes. Já vou fazer esta mudança.

**Comment by RosanaMascena** [comment]
Prontinho, corrigido.

**Comment by carlosmoraes-dev** [comment]
Imagina @RosanaMascena, eu também preciso fazer nos meus.
